//! Reusable types for the generic ARM conformance corpus.
//!
//! This crate is an optional convenience: a harness written in Rust can depend
//! on it to load and interpret cases. Any other harness reads `README.md` and
//! parses the tomls itself. The format and its guarantees are specified in
//! `README.md`; the types here just mirror it.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

/// Marker separating the human-authored top of a case file from the
/// machine-generated lower half. `regen` rewrites everything below it.
pub const GENERATED_MARK: &str = "# --- generated by `regen`; do not edit below this line ---";

/// Column at which `regen` wraps the base64 `[bin]` blob.
pub const BASE64_WRAP: usize = 80;

/// Subdirectory (under the crate root) holding the case tomls.
pub fn cases_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("cases")
}

/// Decode assembly mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Mode {
    #[default]
    Arm,
    Thumb,
}

/// What a case observes to form its golden.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Capture {
    /// Final register state (r0..r12, r14) and NZCV. The default.
    #[default]
    Regs,
    /// Bytes the program wrote to the host output.
    Output,
}

/// NZCV condition flags captured after a `regs` case.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Flags {
    pub n: bool,
    pub z: bool,
    pub c: bool,
    pub v: bool,
}

/// A case's expected result (the golden).
#[derive(Debug, Clone)]
pub enum Expected {
    /// `regs` lists r0..r12/r14 that were seeded or ended non-zero; any register
    /// not listed is expected to be zero. r13/r15 are not captured.
    Regs {
        regs: BTreeMap<u8, u32>,
        flags: Flags,
    },
    /// Bytes written to the host output.
    Output(Vec<u8>),
}

/// A fully parsed case: human-authored input plus the generated lower half.
#[derive(Debug, Clone)]
pub struct Case {
    pub name: String,
    pub description: String,
    pub asm: String,
    pub mode: Mode,
    pub capture: Capture,
    pub in_regs: BTreeMap<u8, u32>,
    pub bin: Vec<u8>,
    pub expected: Expected,
}

/// The case tomls, embedded at compile time. Lets the corpus run where there is
/// no filesystem - notably the browser (wasm) conformance runner - from the exact
/// same committed files the native path reads. `include_dir` tracks the directory
/// so edits (e.g. after `regen`) trigger a rebuild.
static EMBEDDED_CASES: include_dir::Dir<'static> =
    include_dir::include_dir!("$CARGO_MANIFEST_DIR/cases");

/// Load and fully parse every case under [`cases_dir`], sorted by name. Errors
/// if a case is missing its generated half (run `regen` first).
pub fn load_cases() -> Result<Vec<Case>, String> {
    let mut paths: Vec<PathBuf> = fs::read_dir(cases_dir())
        .map_err(|e| format!("read cases dir: {e}"))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "toml"))
        .collect();
    paths.sort();
    paths.iter().map(|p| load_case(p)).collect()
}

/// Parse every embedded case, sorted by name. The filesystem-free twin of
/// [`load_cases`], for hosts (the browser) that cannot read [`cases_dir`].
pub fn embedded_cases() -> Result<Vec<Case>, String> {
    let mut cases: Vec<Case> = EMBEDDED_CASES
        .files()
        .filter(|f| f.path().extension().is_some_and(|x| x == "toml"))
        .map(|f| {
            let name = f.path().file_stem().and_then(|s| s.to_str()).unwrap_or("");
            let text = f.contents_utf8().ok_or_else(|| format!("{name}: case is not UTF-8"))?;
            parse_case(name, text)
        })
        .collect::<Result<_, _>>()?;
    cases.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(cases)
}

/// Parse a single case file.
pub fn load_case(path: &Path) -> Result<Case, String> {
    let text = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let name = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
    parse_case(name, &text)
}

/// Parse a case from its `name` (file stem) and toml `text`. The
/// filesystem-independent core of [`load_case`].
pub fn parse_case(name: &str, text: &str) -> Result<Case, String> {
    let raw: Raw = toml::from_str(text).map_err(|e| format!("{name}: {e}"))?;
    let name = name.to_string();

    let mode = match raw.mode.as_deref() {
        None | Some("arm") => Mode::Arm,
        Some("thumb") => Mode::Thumb,
        Some(other) => return Err(format!("{name}: unknown mode {other:?}")),
    };
    let capture = match raw.capture.as_deref() {
        None | Some("regs") => Capture::Regs,
        Some("output") => Capture::Output,
        Some(other) => return Err(format!("{name}: unknown capture {other:?}")),
    };

    let in_regs = parse_regs(&name, raw.input.map(|s| s.regs).unwrap_or_default())?;
    let bin = raw
        .bin
        .ok_or_else(|| format!("{name}: missing [bin] (run regen)"))?
        .decode()
        .map_err(|e| format!("{name}: {e}"))?;
    let out = raw
        .out
        .ok_or_else(|| format!("{name}: missing [out] (run regen)"))?;

    let expected = match capture {
        Capture::Regs => Expected::Regs {
            regs: parse_regs(&name, out.regs)?,
            flags: out.flags.map(Into::into).unwrap_or_default(),
        },
        Capture::Output => Expected::Output(
            out.output
                .ok_or_else(|| format!("{name}: capture=output but [out].output missing"))?
                .into_bytes(),
        ),
    };

    Ok(Case {
        name,
        description: raw.description,
        asm: raw.asm,
        mode,
        capture,
        in_regs,
        bin,
        expected,
    })
}

/// Map a register name (`r0`..`r15`) to its index.
pub fn reg_index(name: &str) -> Option<u8> {
    let n: u8 = name.strip_prefix('r')?.parse().ok()?;
    (n < 16).then_some(n)
}

fn parse_regs(case: &str, m: BTreeMap<String, i64>) -> Result<BTreeMap<u8, u32>, String> {
    m.into_iter()
        .map(|(k, v)| {
            let i = reg_index(&k).ok_or_else(|| format!("{case}: bad register {k:?}"))?;
            Ok((i, v as u32))
        })
        .collect()
}

/// Standard base64 with all whitespace stripped (PEM-style wrapping allowed).
pub fn decode_base64(s: &str) -> Result<Vec<u8>, String> {
    use base64::Engine;
    let t: String = s.chars().filter(|c| !c.is_whitespace()).collect();
    base64::engine::general_purpose::STANDARD
        .decode(t)
        .map_err(|e| e.to_string())
}

/// Encode bytes as standard base64.
pub fn encode_base64(bytes: &[u8]) -> String {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.encode(bytes)
}

// --- serde mirror of the on-disk toml ---

#[derive(Deserialize)]
struct Raw {
    description: String,
    asm: String,
    mode: Option<String>,
    capture: Option<String>,
    #[serde(rename = "in")]
    input: Option<RawState>,
    bin: Option<RawBin>,
    out: Option<RawOut>,
}

#[derive(Deserialize)]
struct RawState {
    #[serde(default)]
    regs: BTreeMap<String, i64>,
}

#[derive(Deserialize)]
struct RawBin {
    base64: String,
}

impl RawBin {
    fn decode(&self) -> Result<Vec<u8>, String> {
        decode_base64(&self.base64)
    }
}

#[derive(Deserialize)]
struct RawOut {
    #[serde(default)]
    regs: BTreeMap<String, i64>,
    flags: Option<RawFlags>,
    output: Option<String>,
}

#[derive(Deserialize)]
struct RawFlags {
    n: bool,
    z: bool,
    c: bool,
    v: bool,
}

impl From<RawFlags> for Flags {
    fn from(f: RawFlags) -> Self {
        Flags {
            n: f.n,
            z: f.z,
            c: f.c,
            v: f.v,
        }
    }
}
