//! Derive the NON-SUSPENDING host-call set from the dispatch table itself.
//!
//! # What this exists to stop
//! `vita::fast_nid` names the NIDs the transpiler may route through the non-suspending trap
//! (`vitaslop_transpiler::abi::IMPORT_FAST_NAME`). Its admissibility test has always been the
//! SHAPE of the dispatch arm - `cont!(handler(..))`, an unconditional `Continue` around a
//! handler that returns nothing, so it cannot block, reschedule, flip or exit - but the list
//! was WRITTEN OUT, by hand, from one title's host-call profile. That made it wrong in both
//! directions at once: it named 23 of the ~683 arms that qualify (every other title paid a
//! JSPI stack switch for calls that provably never suspend), and keeping it right depended on
//! a human remembering to edit it when a handler grew a parking path.
//!
//! So the list is READ OFF the arms instead. This script parses `src/vita/mod.rs`, finds the
//! one `match func_nid` in `dispatch`, and writes the NIDs whose arm body is EXACTLY
//! `cont!(..)` to `$OUT_DIR/dispatch_cont_only.rs`, which `vita::mod` includes. A handler that
//! grows a parking path stops being `cont!` in the same edit - the arm must return the
//! `SvcOutcome` itself - and leaves the fast set in that same edit, mechanically.
//!
//! # Why the default direction is safe
//! Only the one recognised shape is admitted. Every arm this script does not understand is
//! NOT fast, so a new arm shape, a guard, a binding, a block with statements in front of the
//! `cont!` - any of them - costs an optimisation and can never cost correctness. The one
//! shape that WOULD be dangerous, a pattern that matches more than the constants it names, is
//! refused outright: an admitted pattern must be a `|`-separated list of `module::CONST`
//! paths and nothing else, or the build fails naming the arm.

use std::path::Path;

fn main() {
    let src_path = Path::new("src/vita/mod.rs");
    println!("cargo:rerun-if-changed=src/vita/mod.rs");
    println!("cargo:rerun-if-changed=build.rs");
    let src = std::fs::read_to_string(src_path).expect("src/vita/mod.rs is readable");
    let (nids, arms) = cont_only_nids(&src);
    assert!(
        arms > 500,
        "only {arms} `cont!` arms were recognised in `dispatch` - the parse has come adrift \
         from the source, and a silently SMALL fast set is a performance regression nothing \
         else reports"
    );
    let mut out = String::new();
    out.push_str(
        "// @generated by vitaslop-runtime/build.rs from src/vita/mod.rs - DO NOT EDIT.\n\
         // The NIDs whose `dispatch` arm is exactly `cont!(..)`: an unconditional `Continue`\n\
         // around a handler that returns nothing. See `fast_nid`.\n",
    );
    out.push_str(&format!(
        "/// How many `cont!` ARMS the dispatch table has (an arm may name several NIDs).\n\
         pub const DISPATCH_CONT_ONLY_ARMS: usize = {arms};\n"
    ));
    out.push_str(
        "/// Every NID dispatched through a `cont!` arm, in dispatch order. The universe the\n\
         /// fast set is drawn from - `fast_nid` is this minus the named exclusions.\n\
         pub const DISPATCH_CONT_ONLY: &[u32] = &[\n",
    );
    for n in &nids {
        out.push_str("    ");
        out.push_str(n);
        out.push_str(",\n");
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// Whether `func_nid`'s dispatch arm is exactly `cont!(..)`. A `matches!` rather than\n\
         /// a scan of [`DISPATCH_CONT_ONLY`] so the compiler lowers it to a decision tree.\n\
         fn dispatch_arm_is_cont_only(func_nid: u32) -> bool {\n    matches!(\n        func_nid,\n",
    );
    for (i, n) in nids.iter().enumerate() {
        out.push_str(if i == 0 { "        " } else { "        | " });
        out.push_str(n);
        out.push('\n');
    }
    out.push_str("    )\n}\n");
    let dst = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set"))
        .join("dispatch_cont_only.rs");
    std::fs::write(&dst, out).expect("the generated table is writable");
}

/// The NID constant PATHS (as written, e.g. `gxm_nid::DRAW`) of every `cont!` arm in
/// `dispatch`, plus how many such arms there were.
fn cont_only_nids(src: &str) -> (Vec<String>, usize) {
    let head = "let outcome = match func_nid {";
    assert_eq!(
        src.matches(head).count(),
        1,
        "expected exactly one `{head}` in src/vita/mod.rs - the dispatch table moved or was \
         split, and this script must be pointed at the new one"
    );
    let start = src.find(head).expect("counted above") + head.len();
    let body = strip_comments_and_strings(&src[start..]);
    let arms_src = up_to_matching_close(&body);
    let mut nids = Vec::new();
    let mut arms = 0usize;
    for (pat, body) in split_arms(arms_src) {
        if !is_cont_only(&body) {
            continue;
        }
        arms += 1;
        for part in pat.split('|') {
            let part = part.trim();
            assert!(
                is_nid_const_path(part),
                "the `cont!` arm `{pat} => {body}` in `dispatch` has a pattern this script \
                 will not admit to the fast set: `{part}` is not a `module::CONST` path. A \
                 pattern that binds, guards, or matches a range could route calls the host \
                 never audited through the non-suspending trap, so it is refused here rather \
                 than trusted. Spell the arm as constants, or give it a body that returns its \
                 own `SvcOutcome`."
            );
            nids.push(part.to_string());
        }
    }
    (nids, arms)
}

/// `module::CONST` and nothing else - lowercase module, SCREAMING_CASE constant.
fn is_nid_const_path(s: &str) -> bool {
    let Some((m, c)) = s.split_once("::") else { return false };
    !m.is_empty()
        && m.chars().all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_')
        && !c.is_empty()
        && c.starts_with(|ch: char| ch.is_ascii_uppercase())
        && c.chars().all(|ch| ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_')
}

/// The arm body is EXACTLY one `cont!(..)` call, optionally wrapped in a bare block.
///
/// Deliberately strict. `{ st.do_something(); cont!(..) }` is a real shape in the table and it
/// is REFUSED here: the statements in front of the macro are code this script does not read,
/// and the cost of refusing is one call that keeps paying for a stack switch.
fn is_cont_only(body: &str) -> bool {
    let b = body.trim();
    let b = match (b.strip_prefix('{'), b.strip_suffix('}')) {
        (Some(_), Some(_)) => b[1..b.len() - 1].trim(),
        _ => b,
    };
    let Some(rest) = b.strip_prefix("cont!(") else { return false };
    if !rest.ends_with(')') {
        return false;
    }
    // ...and the macro's own parenthesis must be the one that closes at the end, so
    // `cont!(a) ; cont!(b)` or `cont!(a) + 1` cannot pass.
    let mut depth = 1i32;
    for (i, ch) in rest.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return i == rest.len() - 1;
                }
            }
            _ => {}
        }
    }
    false
}

/// Replace every comment with a space, leaving string and char literals intact (their
/// contents must not be scanned for brackets, and a `//` inside one must not start a
/// comment). A single sequential pass, so a `"` inside a comment is never reached and a
/// `//` inside a string is never reached.
fn strip_comments_and_strings(src: &str) -> String {
    let b = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0usize;
    while i < b.len() {
        match b[i] {
            b'"' => {
                let start = i;
                i += 1;
                while i < b.len() {
                    match b[i] {
                        b'\\' => i += 2,
                        b'"' => {
                            i += 1;
                            break;
                        }
                        _ => i += 1,
                    }
                }
                out.push_str(&src[start..i.min(src.len())]);
            }
            b'\'' => {
                // A char literal (`'a'`, `'\n'`) - a lifetime has no closing quote, so the
                // shape is checked before consuming.
                let lit = if b.get(i + 1) == Some(&b'\\') {
                    (i + 4 <= b.len() && b[i + 3] == b'\'').then_some(i + 4)
                } else {
                    (i + 3 <= b.len() && b[i + 2] == b'\'').then_some(i + 3)
                };
                match lit {
                    Some(end) => {
                        out.push_str(&src[i..end]);
                        i = end;
                    }
                    None => {
                        out.push('\'');
                        i += 1;
                    }
                }
            }
            b'/' if b.get(i + 1) == Some(&b'/') => {
                while i < b.len() && b[i] != b'\n' {
                    i += 1;
                }
                out.push(' ');
            }
            b'/' if b.get(i + 1) == Some(&b'*') => {
                let end = src[i..].find("*/").map_or(b.len(), |p| i + p + 2);
                i = end;
                out.push(' ');
            }
            c => {
                out.push(c as char);
                i += 1;
            }
        }
    }
    out
}

/// The text up to the `}` that closes the block this text is the inside of.
fn up_to_matching_close(s: &str) -> &str {
    let mut depth = 1i32;
    for (i, ch) in s.char_indices() {
        match ch {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => {
                depth -= 1;
                if depth == 0 {
                    return &s[..i];
                }
            }
            _ => {}
        }
    }
    panic!("the `match func_nid` block in src/vita/mod.rs is not closed");
}

/// Split a match body into `(pattern, body)` pairs. Patterns run to the first top-level
/// `=>`; a body is either a braced block or everything up to the next top-level comma.
fn split_arms(src: &str) -> Vec<(String, String)> {
    let b = src.as_bytes();
    let mut arms = Vec::new();
    let mut i = 0usize;
    while i < b.len() {
        while i < b.len() && b[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= b.len() {
            break;
        }
        let pat_start = i;
        let mut depth = 0i32;
        while i < b.len() {
            match b[i] {
                b'(' | b'[' | b'{' => depth += 1,
                b')' | b']' | b'}' => depth -= 1,
                b'=' if depth == 0 && b.get(i + 1) == Some(&b'>') => break,
                _ => {}
            }
            i += 1;
        }
        if i >= b.len() {
            break;
        }
        let pat = src[pat_start..i].trim().to_string();
        i += 2;
        while i < b.len() && b[i].is_ascii_whitespace() {
            i += 1;
        }
        let body_start = i;
        if b.get(i) == Some(&b'{') {
            let mut depth = 0i32;
            while i < b.len() {
                match b[i] {
                    b'{' => depth += 1,
                    b'}' => {
                        depth -= 1;
                        if depth == 0 {
                            i += 1;
                            break;
                        }
                    }
                    _ => {}
                }
                i += 1;
            }
            arms.push((pat, src[body_start..i].to_string()));
            while i < b.len() && (b[i].is_ascii_whitespace() || b[i] == b',') {
                i += 1;
            }
        } else {
            let mut depth = 0i32;
            while i < b.len() {
                match b[i] {
                    b'(' | b'[' | b'{' => depth += 1,
                    b')' | b']' | b'}' => depth -= 1,
                    b',' if depth == 0 => break,
                    _ => {}
                }
                i += 1;
            }
            arms.push((pat, src[body_start..i].trim().to_string()));
            i += 1;
        }
    }
    arms
}
