//! The GPU block encoder must produce what the CPU one produces.
//!
//! # Why this test exists
//! `vitaslop_platform::texenc` moves the ETC2 encoder off the CPU and into a compute shader,
//! because on the target device the CPU encoder runs at about 1 Mtexel/s and a screen transition
//! MEASURED at `BUILD 21,182 ms` while the GPU sat idle at `pass 3.3 ms`. That is worth a great
//! deal, and it is worth exactly nothing if the port is not the same encoder.
//!
//! The WGSL is a line-for-line port of `vitaslop_runtime::etcenc` - the same modifier tables, the
//! same luminance-residual selector shortcut, the same three-pass base search, the same derived
//! EAC multiplier. All of it integer, on both sides, so "the same arithmetic" is a claim that can
//! actually be checked rather than a claim about floating-point luck. This checks it: same
//! images, both encoders, **byte for byte**.
//!
//! Byte equality rather than a quality bound, deliberately. A quality bound would pass a port
//! that had quietly become a different (and possibly worse) encoder as long as it stayed inside
//! the bound, and the whole argument for moving this work is that the picture does not change.
//! If a future adapter forces a divergence, this test is where that decision gets made
//! explicitly.
//!
//! Content-free: every image here is generated by this file. Skips cleanly with no GPU adapter.

use vitaslop_platform::texenc::Transcoder;

/// A device with nothing special asked for. The encoder is plain compute over storage buffers,
/// so it needs no texture-compression feature at all - which is what lets this run on a desktop
/// whose adapter has no ETC2 support and would refuse the finished texture.
fn device() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        force_fallback_adapter: false,
        compatible_surface: None,
        apply_limit_buckets: false,
    }))
    .ok()?;
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-test"),
        required_features: wgpu::Features::empty(),
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// The content shapes the CPU encoder's own error ceilings were written from, plus the two that
/// exercise its special cases (a flat block, and a block with real alpha structure).
///
/// A corpus of noise would test almost nothing: every search in this encoder is about STRUCTURE -
/// which table covers the spread, which flip groups similar texels, whether differential mode can
/// reach the second base - and noise makes all of those answers arbitrary and equally bad. These
/// are the shapes where the two implementations can actually disagree.
fn corpus(w: u32, h: u32) -> Vec<(&'static str, Vec<u8>)> {
    let mut out = Vec::new();
    let make = |f: &dyn Fn(u32, u32) -> [u8; 4]| -> Vec<u8> {
        let mut v = Vec::with_capacity((w * h * 4) as usize);
        for y in 0..h {
            for x in 0..w {
                v.extend_from_slice(&f(x, y));
            }
        }
        v
    };
    out.push(("flat", make(&|_, _| [137, 42, 200, 255])));
    out.push(("luma ramp", make(&|x, _| {
        let v = (x * 255 / (w - 1).max(1)) as u8;
        [v, v, v, 255]
    })));
    out.push(("diagonal ramp", make(&|x, y| {
        let v = ((x + y) * 255 / (w + h - 2).max(1)) as u8;
        [v, v, v, 255]
    })));
    out.push(("single-channel ramp", make(&|x, _| {
        [(x * 255 / (w - 1).max(1)) as u8, 30, 90, 255]
    })));
    // The case the CPU encoder's own notes call out as its weakest - two hues in one block, which
    // the missing T/H/planar modes cannot represent. If the two implementations disagree
    // anywhere, a block whose best encoding is a near-tie is where it happens.
    out.push(("hue ramp", make(&|x, y| {
        let t = (x * 255 / (w - 1).max(1)) as u8;
        [t, 255 - t, ((y * 255) / (h - 1).max(1)) as u8, 255]
    })));
    out.push(("two colour", make(&|x, y| {
        if (x / 2 + y / 2) % 2 == 0 { [220, 30, 30, 255] } else { [30, 30, 220, 255] }
    })));
    // Alpha shapes, for the EAC block: constant (its exact fast path), a ramp, and a hard cutout.
    out.push(("alpha ramp", make(&|_x, y| {
        [180, 90, 40, (y * 255 / (h - 1).max(1)) as u8]
    })));
    out.push(("alpha cutout", make(&|x, y| {
        [180, 90, 40, if (x / 3 + y / 3) % 2 == 0 { 0 } else { 255 }]
    })));
    out.push(("alpha steps", make(&|x, _| [10, 200, 60, ((x % 8) * 36) as u8])));
    out
}

#[test]
fn gpu_etc2_matches_the_cpu_encoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Not a multiple of four in either axis, so the edge-clamp rule in `gather` is covered too -
    // an encoder that agrees on whole blocks and disagrees on the edge ones is an encoder that
    // will disagree on most real textures, since almost none of them are square powers of two
    // all the way down their mip chain.
    for (w, h) in [(16u32, 16u32), (13, 7)] {
        for (name, rgba) in corpus(w, h) {
            for alpha in [false, true] {
                let want = if alpha {
                    vitaslop_runtime::etcenc::encode_etc2_rgba8(w, h, &rgba)
                } else {
                    vitaslop_runtime::etcenc::encode_etc2_rgb8(w, h, &rgba)
                };
                let got = enc.encode_rgba8_readback(&device, &queue, w, h, &rgba, alpha);
                assert_eq!(
                    got.len(),
                    want.len(),
                    "{name} {w}x{h} alpha={alpha}: block count differs"
                );
                // Report the FIRST differing block and both encodings of it. "12,288 bytes
                // differ" says nothing about which of the four searches drifted; one block's two
                // encodings say which mode and which table each side chose.
                let bb = if alpha { 16 } else { 8 };
                for (i, (a, b)) in got.chunks(bb).zip(want.chunks(bb)).enumerate() {
                    assert_eq!(
                        a, b,
                        "{name} {w}x{h} alpha={alpha}: block {i} differs\n  gpu {a:02x?}\n  cpu {b:02x?}"
                    );
                }
            }
        }
    }
}

/// The GPU PVRTC decode and box filter must produce what the CPU ones produce, byte for byte.
///
/// # Why this is the half that most needed a test
/// A PVRTC texel is not block-local. It reads the FOUR blocks whose centres surround it, on a
/// grid shifted by half a block, and the format WRAPS at the edges by construction - so the
/// addressing is exactly the kind that comes out plausible and wrong. On top of that the guest
/// stores its blocks in Morton order over a power-of-two-padded grid, which the shader has to
/// walk identically. A decode that is off by one block reads as a texture that is nearly right,
/// which is the hardest kind of defect to see in a running game and the easiest to see here.
///
/// The mip filter rides along: levels past the guest's own are box-filtered on the GPU, and the
/// chain is compared level by level, so an error in the filter cannot hide inside a later level.
#[test]
fn gpu_pvrtc_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Every combination that changes the addressing: both PVRTC generations, both bit rates,
    // Morton and linear block order.
    for two in [false, true] {
        for four_bpp in [false, true] {
            for swizzled in [false, true] {
                let (w, h) = (32u32, 32u32);
                let base_format: u32 = match (two, four_bpp) {
                    (false, false) => 0x80,
                    (false, true) => 0x81,
                    (true, false) => 0x82,
                    (true, true) => 0x83,
                };
                // SWIZZLED / LINEAR `SceGxmTextureType` selectors.
                let tex_type: u32 = if swizzled { 0 } else { 3 };
                let levels = vitaslop_runtime::render::max_mip_levels(w, h);
                // Deterministic pseudo-random block words. The decoder accepts any 64 bits, and
                // random ones exercise every colour mode, both opacity flags, the hard-transition
                // bit and every modulation code - which a hand-written block cannot.
                let mut total = 0usize;
                for l in 0..levels {
                    let Some(ll) =
                        vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
                    else {
                        break;
                    };
                    total += ll.bytes as usize;
                }
                let mut seed = 0x243f_6a88_85a3_08d3u64;
                let bytes: Vec<u8> = (0..total)
                    .map(|_| {
                        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                        (seed >> 33) as u8
                    })
                    .collect();

                let plan = build_plan(base_format, tex_type, w, h, levels, &bytes, two, four_bpp);
                let got = enc.decode_chain_readback(&device, &queue, &plan);

                // The CPU reference: the guest's own levels through `pvrtc::decode_face`, then
                // the box filter for the rest - which is exactly what `transcoded_source` does.
                let variant = vitaslop_runtime::pvrtc::Variant::from_base_format(base_format).unwrap();
                let mut want: Vec<(u32, u32, Vec<u8>)> = Vec::new();
                for l in 0..levels {
                    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
                        .unwrap();
                    let off =
                        vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l)
                            .unwrap() as usize;
                    let mut px = vec![0u8; (ll.width * ll.height * 4) as usize];
                    vitaslop_runtime::pvrtc::decode_face(
                        &bytes[off..],
                        ll.width,
                        ll.height,
                        variant,
                        swizzled,
                        &mut px,
                    );
                    want.push((ll.width, ll.height, px));
                }
                let label = format!("pvrtc2={two} 4bpp={four_bpp} swizzled={swizzled}");
                assert_eq!(got.len(), want.len(), "{label}: level count");
                for (i, ((gw, gh, g), (ww, wh, wv))) in got.iter().zip(&want).enumerate() {
                    assert_eq!((gw, gh), (ww, wh), "{label}: level {i} dimensions");
                    let first = g.iter().zip(wv).position(|(a, b)| a != b);
                    assert!(
                        first.is_none(),
                        "{label}: level {i} ({ww}x{wh}) differs at byte {} - gpu {:?} cpu {:?}",
                        first.unwrap(),
                        &g[first.unwrap()..(first.unwrap() + 4).min(g.len())],
                        &wv[first.unwrap()..(first.unwrap() + 4).min(wv.len())],
                    );
                }
            }
        }
    }
}

/// The GPU BC1/BC2/BC3 decode must produce what the CPU one produces, byte for byte.
///
/// # Why this path exists at all, when the guest's BC blocks usually pass straight through
/// `UBC1/2/3` ARE BC1/2/3, so on any adapter with `texture-compression-bc` they are handed over
/// untouched. The target device's adapter has no BC, and there the only options are an RGBA8
/// expansion at four times the size or a decode plus a re-encode - which used to be the most
/// expensive path in the whole texture pipeline and was gated behind a memory-pressure test for
/// exactly that reason. On the GPU it costs nothing, so the gate came off, and this is what says
/// the decode behind it is right.
///
/// The three formats differ in ways that are easy to get subtly wrong and hard to see: BC1's
/// 3-colour punch-through mode is selected by comparing the two stored endpoints, BC2's alpha is
/// two nibbles a byte with the LOW one first, and BC3's is a 3-bit index stream packed
/// little-endian ACROSS byte boundaries with two different interpolation rules depending on which
/// endpoint is larger.
#[test]
fn gpu_bc_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    for base_format in [0x85u32, 0x86, 0x87] {
        for swizzled in [false, true] {
            let (w, h) = (32u32, 32u32);
            let tex_type: u32 = if swizzled { 0 } else { 3 };
            let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
            // Random block bits: every mode, both endpoint orderings (so BC1's punch-through and
            // BC3's two alpha rules are both exercised), every index.
            let mut seed = 0xdead_beef_1234_5678u64;
            let bytes: Vec<u8> = (0..ll.bytes as usize)
                .map(|_| {
                    seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                    (seed >> 33) as u8
                })
                .collect();
            let plan = build_bc_plan(base_format, tex_type, w, h, &bytes);
            let got = enc.decode_chain_readback(&device, &queue, &plan);
            let want = vitaslop_runtime::render::decode_texture_rgba8(
                &bc_texture(base_format, tex_type, w, h, &bytes),
            );
            let label = format!("{base_format:#04x} swizzled={swizzled}");
            assert_eq!((got[0].0, got[0].1), (want.0, want.1), "{label}: dimensions");
            let first = got[0].2.iter().zip(&want.2).position(|(a, b)| a != b);
            assert!(
                first.is_none(),
                "{label}: differs at byte {} - gpu {:?} cpu {:?}",
                first.unwrap(),
                &got[0].2[first.unwrap()..(first.unwrap() + 4).min(got[0].2.len())],
                &want.2[first.unwrap()..(first.unwrap() + 4).min(want.2.len())],
            );
        }
    }
}

/// A single-level BC texture, as the capture would present it.
fn bc_texture(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    bytes: &[u8],
) -> vitaslop_runtime::capture::BoundTexture {
    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
    vitaslop_runtime::capture::BoundTexture {
        unit: 0,
        base_format,
        swizzle: 0,
        tex_type,
        width: w,
        height: h,
        stride: ll.stride,
        faces: 1,
        face_bytes: ll.bytes,
        levels: 1,
        data_addr: 0,
        pixels: bytes.into(),
        u_addr_mode: 0,
        v_addr_mode: 0,
        lod_bias: 0,
        mag_filter: 0,
        min_filter: 0,
        mip_filter: 0,
        gamma: 0,

    }
}

fn build_bc_plan(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    bytes: &[u8],
) -> vitaslop_platform::gpu::GpuTranscode {
    use vitaslop_platform::gpu::SourceCodec;
    let mut plan = build_plan(base_format, tex_type, w, h, 1, bytes, false, true);
    plan.codec = SourceCodec::Bc { base_format };
    plan.levels = 1;
    plan
}

/// The box filter, on the levels the guest did NOT supply.
///
/// Split from the decode test because the two fail for different reasons and a combined one
/// would report the filter's fault as a decode fault: here the guest declares ONE level, so
/// every level below it is the shader's own filter against `halve_rgba8`.
#[test]
fn gpu_mip_filter_matches_the_cpu() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // 24x24 rather than a power of two: an odd level (3x3 -> 1x1) is where the box filter's
    // edge-clamp rule bites, and it is the rule the two implementations could most easily
    // disagree about.
    let (w, h) = (24u32, 24u32);
    let base_format = 0x81u32;
    let tex_type = 3u32;
    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
    let mut seed = 0x9e37_79b9_7f4a_7c15u64;
    let bytes: Vec<u8> = (0..ll.bytes as usize)
        .map(|_| {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            (seed >> 33) as u8
        })
        .collect();
    let levels = vitaslop_runtime::render::max_mip_levels(w, h);
    // ONE guest level, so levels 1.. are the shader's own filter.
    let plan = build_plan(base_format, tex_type, w, h, 1, &bytes, false, true);
    let plan = vitaslop_platform::gpu::GpuTranscode { levels, ..plan };
    let got = enc.decode_chain_readback(&device, &queue, &plan);

    let variant = vitaslop_runtime::pvrtc::Variant::from_base_format(base_format).unwrap();
    let mut px = vec![0u8; (w * h * 4) as usize];
    vitaslop_runtime::pvrtc::decode_face(&bytes, w, h, variant, false, &mut px);
    let mut want = vec![(w, h, px)];
    for l in 1..levels as usize {
        let (pw, ph, prev) = &want[l - 1];
        let (nw, nh, next) = vitaslop_runtime::render::halve_rgba8(*pw, *ph, prev);
        want.push((nw, nh, next));
    }
    assert_eq!(got.len(), want.len());
    for (i, ((gw, gh, g), (ww, wh, wv))) in got.iter().zip(&want).enumerate() {
        assert_eq!((gw, gh), (ww, wh), "level {i} dimensions");
        assert_eq!(g, wv, "level {i} ({ww}x{wh}) differs");
    }
}

/// The plan the runtime would build for this texture, assembled here so the test does not need
/// an ETC2 adapter to reach the runtime's own (adapter-gated) builder.
#[allow(clippy::too_many_arguments)]
fn build_plan(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    levels: u32,
    bytes: &[u8],
    two: bool,
    four_bpp: bool,
) -> vitaslop_platform::gpu::GpuTranscode {
    use vitaslop_platform::gpu::{GpuTranscode, SourceCodec, SrcLevel};
    let swizzled = vitaslop_runtime::render::swizzled_type(tex_type);
    let src_levels = (0..levels)
        .map(|l| {
            let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l).unwrap();
            SrcLevel {
                byte_offset: vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l)
                    .unwrap(),
                width: ll.width,
                height: ll.height,
                blocks_x: ll.blocks_x,
                blocks_y: ll.blocks_y,
                padded_x: if swizzled { ll.blocks_x.next_power_of_two() } else { ll.blocks_x },
                padded_y: if swizzled { ll.blocks_y.next_power_of_two() } else { ll.blocks_y },
                swizzled,
            }
        })
        .collect();
    GpuTranscode {
        src: bytes.into(),
        codec: SourceCodec::Pvrtc { two, four_bpp },
        width: w,
        height: h,
        levels,
        src_levels,
    }
}

/// The per-level `copyBufferToTexture` the transcoder records must be one the driver ACCEPTS.
///
/// # This is the test whose absence shipped a broken build
/// The copy extent was each level's LOGICAL size. WebGPU validates a compressed copy against the
/// level's PHYSICAL extent - the logical size rounded up to whole blocks - so a 2x2 mip level of
/// a 4x4-block format has to be copied as 4x4. The driver rejected it with
/// `copySize.height (2) is not a multiple of compressed texture format block height (4)`, the
/// whole command buffer became invalid, and every transcoded texture was created and never
/// written. On the device that read as "no textures are right".
///
/// It was not caught because the copy was believed untestable here: this adapter has no ETC2, so
/// `Transcoder::run` returns `None` and the path stays dormant. That reasoning was wrong. **The
/// copy's rules are properties of the BLOCK GEOMETRY, not of the family** - BC1 and `Etc2Rgb8`
/// are both 4x4 blocks at 8 bytes, BC3 and `Etc2Rgba8` both 4x4 at 16 - so the copy can be driven
/// with whichever block format the adapter DOES have, and it exercises the same arithmetic.
///
/// Native wgpu panics on an uncaptured validation error, so an illegal copy fails this test
/// rather than passing quietly.
#[test]
fn the_recorded_copies_are_accepted_by_the_driver() {
    let Some((device, queue)) = device_with_block_compression() else {
        eprintln!("no GPU adapter with a block-compressed format - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    let f = device.features();
    // Whichever family this adapter has, at both block sizes. The 8-byte and 16-byte cases have
    // different row pitches and so different padding, and only one of them is exercised by any
    // single texture.
    let pairs: Vec<(vitaslop_platform::gpu::BlockFormat, wgpu::TextureFormat)> =
        if f.contains(wgpu::Features::TEXTURE_COMPRESSION_BC) {
            vec![
                (vitaslop_platform::gpu::BlockFormat::Bc1, wgpu::TextureFormat::Bc1RgbaUnorm),
                (vitaslop_platform::gpu::BlockFormat::Bc3, wgpu::TextureFormat::Bc3RgbaUnorm),
            ]
        } else {
            vec![
                (vitaslop_platform::gpu::BlockFormat::Etc2Rgb8, wgpu::TextureFormat::Etc2Rgb8Unorm),
                (
                    vitaslop_platform::gpu::BlockFormat::Etc2Rgba8,
                    wgpu::TextureFormat::Etc2Rgba8Unorm,
                ),
            ]
        };
    // Sizes whose chains reach BELOW the block size, which is where the bug lived, plus a
    // non-square one and the largest atlas this title actually binds.
    for (w, h) in [(2048u32, 2048u32), (1024, 512), (64, 64), (8, 8), (4, 4)] {
        for &(format, wgpu_format) in &pairs {
            enc.copy_geometry_selftest(&device, &queue, w, h, format, wgpu_format);
        }
    }
}

/// The SHIPPED path, end to end, into a real ETC2 texture on a real adapter, read back and
/// compared against the CPU pipeline block for block.
///
/// # Why this exists, and why "the desktop has no ETC2" was wrong
/// Every piece of the transcoder was verified individually - the PVRTC decode, the box filter and
/// the ETC2 encoder are each bit-identical to the CPU code they replace - and `Transcoder::run`
/// itself, which wires them together and copies the result into a texture, was never executed
/// anywhere. It was declared untestable because the default adapter here exposes only BC. That
/// was a statement about ONE adapter, not about the machine: `enumerate_adapters` finds an Intel
/// Arc iGPU on Vulkan that exposes **bc AND etc2**, and everything the shipped path does runs on
/// it unchanged.
///
/// The cost of not looking was a build that reached the user's phone with every transcoded
/// texture created and never written.
///
/// What this checks that nothing else does: the scratch buffer sizes, the uniform slot offsets
/// and dynamic offsets, the dispatch counts, the ORDER of decode -> filter -> encode inside one
/// compute pass (the mip filter reads what the dispatch before it wrote), the row padding, and
/// the per-level copies - by reading the finished texture's actual bytes.
#[test]
fn gpu_transcode_round_trips_through_a_real_etc2_texture() {
    let Some((device, queue)) = device_with_etc2() else {
        eprintln!("no adapter on this machine exposes ETC2 - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Every (source, target) pair the device actually takes: both PVRTC generations at both bit
    // rates, both addressing modes, and the BC formats an ETC2-only adapter has to re-encode -
    // against both ETC2 targets, because the alpha one emits a second block per 4x4 and so has a
    // different row pitch, a different buffer size and a different copy.
    for base_format in [0x80u32, 0x81, 0x82, 0x83, 0x85, 0x86, 0x87] {
        for tex_type in [0u32, 3] {
            for alpha in [false, true] {
                round_trip_one(&device, &queue, &enc, base_format, tex_type, alpha);
            }
        }
    }
}

fn round_trip_one(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    enc: &Transcoder,
    base_format: u32,
    tex_type: u32,
    alpha: bool,
) {
    use vitaslop_platform::gpu::{BlockFormat, CompressedData, CompressedUpload, SourceCodec};
    // 32x32, so the chain runs below the block size - which is where the copy extent was wrong.
    let (w, h) = (32u32, 32u32);
    let label = format!("{base_format:#04x} type {tex_type} alpha {alpha}");
    let levels = vitaslop_runtime::render::max_mip_levels(w, h);
    let mut total = 0usize;
    for l in 0..levels {
        let Some(ll) = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
        else {
            break;
        };
        total += ll.bytes as usize;
    }
    let mut seed = 0x1234_5678_9abc_def0u64;
    let bytes: Vec<u8> = (0..total)
        .map(|_| {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            (seed >> 33) as u8
        })
        .collect();
    // The codec the runtime would pick for this base format, chosen the same way it does.
    let codec = match vitaslop_runtime::pvrtc::Variant::from_base_format(base_format) {
        Some(v) => SourceCodec::Pvrtc { two: v.two, four_bpp: v.four_bpp },
        None => SourceCodec::Bc { base_format },
    };
    let mut plan = build_plan(base_format, tex_type, w, h, levels, &bytes, false, true);
    plan.codec = codec;
    let format = if alpha { BlockFormat::Etc2Rgba8 } else { BlockFormat::Etc2Rgb8 };
    let block_bytes = format.block_bytes();
    let upload = CompressedUpload {
        format,
        width: w,
        height: h,
        levels,
        transcoded: true,
        data: CompressedData::Gpu(plan.clone()),
    };

    let texture = enc
        .run(&device, &queue, &upload, &plan, false)
        .expect("this adapter has ETC2, so the transcode must not decline");

    // The CPU pipeline over the same bytes: decode every guest level, then encode each. Each of
    // those steps is separately proved identical to its shader, so any difference here is in the
    // WIRING - which is the point.
    let mut chain: Vec<(u32, u32, Vec<u8>)> = Vec::new();
    for l in 0..levels {
        let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l).unwrap();
        let off =
            vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l).unwrap() as usize;
        let px = match vitaslop_runtime::pvrtc::Variant::from_base_format(base_format) {
            Some(variant) => {
                let mut px = vec![0u8; (ll.width * ll.height * 4) as usize];
                vitaslop_runtime::pvrtc::decode_face(
                    &bytes[off..],
                    ll.width,
                    ll.height,
                    variant,
                    vitaslop_runtime::render::swizzled_type(tex_type),
                    &mut px,
                );
                px
            }
            None => {
                let view = bc_texture(base_format, tex_type, ll.width, ll.height, &bytes[off..]);
                vitaslop_runtime::render::decode_texture_rgba8(&view).2
            }
        };
        chain.push((ll.width, ll.height, px));
    }

    for (i, (lw, lh, rgba)) in chain.iter().enumerate() {
        let want = if alpha {
            vitaslop_runtime::etcenc::encode_etc2_rgba8(*lw, *lh, rgba)
        } else {
            vitaslop_runtime::etcenc::encode_etc2_rgb8(*lw, *lh, rgba)
        };
        let got = read_back_level(device, queue, &texture, i as u32, *lw, *lh, block_bytes);
        assert_eq!(got.len(), want.len(), "{label} level {i} ({lw}x{lh}): block count");
        for (b, (a, e)) in got.chunks(block_bytes as usize).zip(want.chunks(block_bytes as usize)).enumerate()
        {
            assert_eq!(
                a, e,
                "{label} level {i} ({lw}x{lh}) block {b} differs\n  gpu texture {a:02x?}\n  cpu        {e:02x?}"
            );
        }
    }
    texture.destroy();
}

/// One mip level of a compressed texture, read back and unpadded.
fn read_back_level(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    level: u32,
    width: u32,
    height: u32,
    block_bytes: u32,
) -> Vec<u8> {
    let blocks_x = width.div_ceil(4);
    let blocks_y = height.div_ceil(4);
    let row = (blocks_x * block_bytes).div_ceil(256) * 256;
    let size = (row * blocks_y) as u64;
    let buf = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("readback"),
        size,
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let mut enc = device.create_command_encoder(&Default::default());
    enc.copy_texture_to_buffer(
        wgpu::TexelCopyTextureInfo {
            texture,
            mip_level: level,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::TexelCopyBufferInfo {
            buffer: &buf,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: Some(blocks_y),
            },
        },
        wgpu::Extent3d { width: blocks_x * 4, height: blocks_y * 4, depth_or_array_layers: 1 },
    );
    queue.submit([enc.finish()]);
    let slice = buf.slice(..);
    slice.map_async(wgpu::MapMode::Read, |_| {});
    let _ = device.poll(wgpu::PollType::Wait { submission_index: None, timeout: None });
    let view = slice.get_mapped_range().expect("the poll above waited for the map");
    let mut out = Vec::with_capacity((blocks_x * blocks_y * block_bytes) as usize);
    for by in 0..blocks_y {
        let start = (by * row) as usize;
        out.extend_from_slice(&view[start..start + (blocks_x * block_bytes) as usize]);
    }
    drop(view);
    buf.unmap();
    out
}

/// An adapter that exposes ETC2, wherever on this machine it is.
///
/// `request_adapter` returns ONE adapter - the high-performance one - and on this machine that is
/// a discrete NVIDIA part with BC and no ETC2. Enumerating finds the integrated Intel GPU on
/// Vulkan, which has both. The difference between those two calls is the difference between "the
/// shipped path cannot be tested here" and this test.
fn device_with_etc2() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.enumerate_adapters(wgpu::Backends::all()))
        .into_iter()
        .find(|a| a.features().contains(wgpu::Features::TEXTURE_COMPRESSION_ETC2))?;
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-etc2-test"),
        required_features: wgpu::Features::TEXTURE_COMPRESSION_ETC2,
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// A device that has SOME block-compressed format, so the copy can be recorded into a real
/// texture. Which family it is does not matter - see `copy_geometry_selftest`.
fn device_with_block_compression() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        force_fallback_adapter: false,
        compatible_surface: None,
        apply_limit_buckets: false,
    }))
    .ok()?;
    let want = adapter.features()
        & (wgpu::Features::TEXTURE_COMPRESSION_BC | wgpu::Features::TEXTURE_COMPRESSION_ETC2);
    if want.is_empty() {
        return None;
    }
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-copy-test"),
        required_features: want,
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// The EAC ascending-modifier order the shader hard-codes must be the one the CPU DERIVES from
/// the tables.
///
/// The CPU builds it with a compile-time selection sort over each table's eight modifiers,
/// precisely so a hand-copied ordering cannot disagree with the tables. WGSL has no const
/// evaluation that could do the same, so the shader writes it out - and a written-out ordering
/// that drifts from the tables encodes every alpha wrong, silently, in a way no single block
/// comparison would obviously explain. This is the guard for that one constant.
#[test]
fn gpu_eac_order_matches_the_cpu() {
    for table in 0..16 {
        let mut want: Vec<usize> = (0..8).collect();
        want.sort_by_key(|&s| vitaslop_runtime::etcenc::eac_modifier(table, s));
        assert_eq!(
            want,
            vec![3, 2, 1, 0, 4, 5, 6, 7],
            "table {table}'s ascending order is not the one texenc.wgsl hard-codes"
        );
    }
}
