//! The GPU block encoder must produce what the CPU one produces.
//!
//! # Why this test exists
//! `vitaslop_platform::texenc` moves the ETC2 encoder off the CPU and into a compute shader,
//! because on the target device the CPU encoder runs at about 1 Mtexel/s and a screen transition
//! MEASURED at `BUILD 21,182 ms` while the GPU sat idle at `pass 3.3 ms`. That is worth a great
//! deal, and it is worth exactly nothing if the port is not the same encoder.
//!
//! The WGSL is a line-for-line port of `vitaslop_runtime::etcenc` - the same modifier tables, the
//! same luminance-residual selector shortcut, the same three-pass base search, the same derived
//! EAC multiplier. All of it integer, on both sides, so "the same arithmetic" is a claim that can
//! actually be checked rather than a claim about floating-point luck. This checks it: same
//! images, both encoders, **byte for byte**.
//!
//! Byte equality rather than a quality bound, deliberately. A quality bound would pass a port
//! that had quietly become a different (and possibly worse) encoder as long as it stayed inside
//! the bound, and the whole argument for moving this work is that the picture does not change.
//! If a future adapter forces a divergence, this test is where that decision gets made
//! explicitly.
//!
//! Content-free: every image here is generated by this file. Skips cleanly with no GPU adapter.

use vitaslop_platform::texenc::Transcoder;

/// A device with nothing special asked for. The encoder is plain compute over storage buffers,
/// so it needs no texture-compression feature at all - which is what lets this run on a desktop
/// whose adapter has no ETC2 support and would refuse the finished texture.
fn device() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        force_fallback_adapter: false,
        compatible_surface: None,
        apply_limit_buckets: false,
    }))
    .ok()?;
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-test"),
        required_features: wgpu::Features::empty(),
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// The content shapes the CPU encoder's own error ceilings were written from, plus the two that
/// exercise its special cases (a flat block, and a block with real alpha structure).
///
/// A corpus of noise would test almost nothing: every search in this encoder is about STRUCTURE -
/// which table covers the spread, which flip groups similar texels, whether differential mode can
/// reach the second base - and noise makes all of those answers arbitrary and equally bad. These
/// are the shapes where the two implementations can actually disagree.
fn corpus(w: u32, h: u32) -> Vec<(&'static str, Vec<u8>)> {
    let mut out = Vec::new();
    let make = |f: &dyn Fn(u32, u32) -> [u8; 4]| -> Vec<u8> {
        let mut v = Vec::with_capacity((w * h * 4) as usize);
        for y in 0..h {
            for x in 0..w {
                v.extend_from_slice(&f(x, y));
            }
        }
        v
    };
    out.push(("flat", make(&|_, _| [137, 42, 200, 255])));
    out.push(("luma ramp", make(&|x, _| {
        let v = (x * 255 / (w - 1).max(1)) as u8;
        [v, v, v, 255]
    })));
    out.push(("diagonal ramp", make(&|x, y| {
        let v = ((x + y) * 255 / (w + h - 2).max(1)) as u8;
        [v, v, v, 255]
    })));
    out.push(("single-channel ramp", make(&|x, _| {
        [(x * 255 / (w - 1).max(1)) as u8, 30, 90, 255]
    })));
    // The case the CPU encoder's own notes call out as its weakest - two hues in one block, which
    // the missing T/H/planar modes cannot represent. If the two implementations disagree
    // anywhere, a block whose best encoding is a near-tie is where it happens.
    out.push(("hue ramp", make(&|x, y| {
        let t = (x * 255 / (w - 1).max(1)) as u8;
        [t, 255 - t, ((y * 255) / (h - 1).max(1)) as u8, 255]
    })));
    out.push(("two colour", make(&|x, y| {
        if (x / 2 + y / 2) % 2 == 0 { [220, 30, 30, 255] } else { [30, 30, 220, 255] }
    })));
    // Alpha shapes, for the EAC block: constant (its exact fast path), a ramp, and a hard cutout.
    out.push(("alpha ramp", make(&|_x, y| {
        [180, 90, 40, (y * 255 / (h - 1).max(1)) as u8]
    })));
    out.push(("alpha cutout", make(&|x, y| {
        [180, 90, 40, if (x / 3 + y / 3) % 2 == 0 { 0 } else { 255 }]
    })));
    out.push(("alpha steps", make(&|x, _| [10, 200, 60, ((x % 8) * 36) as u8])));
    out
}

#[test]
fn gpu_etc2_matches_the_cpu_encoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Not a multiple of four in either axis, so the edge-clamp rule in `gather` is covered too -
    // an encoder that agrees on whole blocks and disagrees on the edge ones is an encoder that
    // will disagree on most real textures, since almost none of them are square powers of two
    // all the way down their mip chain.
    for (w, h) in [(16u32, 16u32), (13, 7)] {
        for (name, rgba) in corpus(w, h) {
            for alpha in [false, true] {
                let want = if alpha {
                    vitaslop_runtime::etcenc::encode_etc2_rgba8(w, h, &rgba)
                } else {
                    vitaslop_runtime::etcenc::encode_etc2_rgb8(w, h, &rgba)
                };
                let got = enc.encode_rgba8_readback(&device, &queue, w, h, &rgba, alpha);
                assert_eq!(
                    got.len(),
                    want.len(),
                    "{name} {w}x{h} alpha={alpha}: block count differs"
                );
                // Report the FIRST differing block and both encodings of it. "12,288 bytes
                // differ" says nothing about which of the four searches drifted; one block's two
                // encodings say which mode and which table each side chose.
                let bb = if alpha { 16 } else { 8 };
                for (i, (a, b)) in got.chunks(bb).zip(want.chunks(bb)).enumerate() {
                    assert_eq!(
                        a, b,
                        "{name} {w}x{h} alpha={alpha}: block {i} differs\n  gpu {a:02x?}\n  cpu {b:02x?}"
                    );
                }
            }
        }
    }
}

/// The GPU PVRTC decode and box filter must produce what the CPU ones produce, byte for byte.
///
/// # Why this is the half that most needed a test
/// A PVRTC texel is not block-local. It reads the FOUR blocks whose centres surround it, on a
/// grid shifted by half a block, and the format WRAPS at the edges by construction - so the
/// addressing is exactly the kind that comes out plausible and wrong. On top of that the guest
/// stores its blocks in Morton order over a power-of-two-padded grid, which the shader has to
/// walk identically. A decode that is off by one block reads as a texture that is nearly right,
/// which is the hardest kind of defect to see in a running game and the easiest to see here.
///
/// The mip filter rides along: levels past the guest's own are box-filtered on the GPU, and the
/// chain is compared level by level, so an error in the filter cannot hide inside a later level.
#[test]
fn gpu_pvrtc_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Every combination that changes the addressing: both PVRTC generations, both bit rates,
    // Morton and linear block order.
    for two in [false, true] {
        for four_bpp in [false, true] {
            for swizzled in [false, true] {
                let (w, h) = (32u32, 32u32);
                let base_format: u32 = match (two, four_bpp) {
                    (false, false) => 0x80,
                    (false, true) => 0x81,
                    (true, false) => 0x82,
                    (true, true) => 0x83,
                };
                // SWIZZLED / LINEAR `SceGxmTextureType` selectors.
                let tex_type: u32 = if swizzled { 0 } else { 3 };
                let levels = vitaslop_runtime::render::max_mip_levels(w, h);
                // Deterministic pseudo-random block words. The decoder accepts any 64 bits, and
                // random ones exercise every colour mode, both opacity flags, the hard-transition
                // bit and every modulation code - which a hand-written block cannot.
                let mut total = 0usize;
                for l in 0..levels {
                    let Some(ll) =
                        vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
                    else {
                        break;
                    };
                    total += ll.bytes as usize;
                }
                let mut seed = 0x243f_6a88_85a3_08d3u64;
                let bytes: Vec<u8> = (0..total)
                    .map(|_| {
                        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                        (seed >> 33) as u8
                    })
                    .collect();

                let plan = build_plan(base_format, tex_type, w, h, levels, &bytes, two, four_bpp);
                let got = enc.decode_chain_readback(&device, &queue, &plan);

                // The CPU reference: the guest's own levels through `pvrtc::decode_face`, then
                // the box filter for the rest - which is exactly what `transcoded_source` does.
                let variant = vitaslop_runtime::pvrtc::Variant::from_base_format(base_format).unwrap();
                let mut want: Vec<(u32, u32, Vec<u8>)> = Vec::new();
                for l in 0..levels {
                    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
                        .unwrap();
                    let off =
                        vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l)
                            .unwrap() as usize;
                    let mut px = vec![0u8; (ll.width * ll.height * 4) as usize];
                    vitaslop_runtime::pvrtc::decode_face(
                        &bytes[off..],
                        ll.width,
                        ll.height,
                        variant,
                        swizzled,
                        &mut px,
                    );
                    want.push((ll.width, ll.height, px));
                }
                let label = format!("pvrtc2={two} 4bpp={four_bpp} swizzled={swizzled}");
                assert_eq!(got.len(), want.len(), "{label}: level count");
                for (i, ((gw, gh, g), (ww, wh, wv))) in got.iter().zip(&want).enumerate() {
                    assert_eq!((gw, gh), (ww, wh), "{label}: level {i} dimensions");
                    let first = g.iter().zip(wv).position(|(a, b)| a != b);
                    assert!(
                        first.is_none(),
                        "{label}: level {i} ({ww}x{wh}) differs at byte {} - gpu {:?} cpu {:?}",
                        first.unwrap(),
                        &g[first.unwrap()..(first.unwrap() + 4).min(g.len())],
                        &wv[first.unwrap()..(first.unwrap() + 4).min(wv.len())],
                    );
                }
            }
        }
    }
}

/// The GPU BC1/BC2/BC3 decode must produce what the CPU one produces, byte for byte.
///
/// # Why this path exists at all, when the guest's BC blocks usually pass straight through
/// `UBC1/2/3` ARE BC1/2/3, so on any adapter with `texture-compression-bc` they are handed over
/// untouched. The target device's adapter has no BC, and there the only options are an RGBA8
/// expansion at four times the size or a decode plus a re-encode - which used to be the most
/// expensive path in the whole texture pipeline and was gated behind a memory-pressure test for
/// exactly that reason. On the GPU it costs nothing, so the gate came off, and this is what says
/// the decode behind it is right.
///
/// The three formats differ in ways that are easy to get subtly wrong and hard to see: BC1's
/// 3-colour punch-through mode is selected by comparing the two stored endpoints, BC2's alpha is
/// two nibbles a byte with the LOW one first, and BC3's is a 3-bit index stream packed
/// little-endian ACROSS byte boundaries with two different interpolation rules depending on which
/// endpoint is larger.
#[test]
fn gpu_bc_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    for base_format in [0x85u32, 0x86, 0x87] {
        for swizzled in [false, true] {
            let (w, h) = (32u32, 32u32);
            let tex_type: u32 = if swizzled { 0 } else { 3 };
            let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
            // Random block bits: every mode, both endpoint orderings (so BC1's punch-through and
            // BC3's two alpha rules are both exercised), every index.
            let mut seed = 0xdead_beef_1234_5678u64;
            let bytes: Vec<u8> = (0..ll.bytes as usize)
                .map(|_| {
                    seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
                    (seed >> 33) as u8
                })
                .collect();
            let plan = build_bc_plan(base_format, tex_type, w, h, &bytes);
            let got = enc.decode_chain_readback(&device, &queue, &plan);
            let want = vitaslop_runtime::render::decode_texture_rgba8(
                &bc_texture(base_format, tex_type, w, h, &bytes),
            );
            let label = format!("{base_format:#04x} swizzled={swizzled}");
            assert_eq!((got[0].0, got[0].1), (want.0, want.1), "{label}: dimensions");
            let first = got[0].2.iter().zip(&want.2).position(|(a, b)| a != b);
            assert!(
                first.is_none(),
                "{label}: differs at byte {} - gpu {:?} cpu {:?}",
                first.unwrap(),
                &got[0].2[first.unwrap()..(first.unwrap() + 4).min(got[0].2.len())],
                &want.2[first.unwrap()..(first.unwrap() + 4).min(want.2.len())],
            );
        }
    }
}

/// A single-level BC texture, as the capture would present it.
fn bc_texture(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    bytes: &[u8],
) -> vitaslop_runtime::capture::BoundTexture {
    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
    vitaslop_runtime::capture::BoundTexture {
        // A fixture: a DISTINCT buffer, so a distinct identity - two fixtures sharing
        // one id would collide in every cache keyed on it.
        pixels_id: vitaslop_runtime::capture::next_pixels_id(),
        unit: 0,
        base_format,
        swizzle: 0,
        tex_type,
        width: w,
        height: h,
        stride: ll.stride,
        faces: 1,
        face_bytes: ll.bytes,
        levels: 1,
        data_addr: 0,
        pixels: bytes.into(),
        u_addr_mode: 0,
        v_addr_mode: 0,
        lod_bias: 0,
        mag_filter: 0,
        min_filter: 0,
        mip_filter: 0,
        gamma: 0,

    }
}

fn build_bc_plan(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    bytes: &[u8],
) -> vitaslop_platform::gpu::GpuTranscode {
    use vitaslop_platform::gpu::SourceCodec;
    let mut plan = build_plan(base_format, tex_type, w, h, 1, bytes, false, true);
    plan.codec = SourceCodec::Bc { base_format };
    plan.levels = 1;
    plan
}

/// The box filter, on the levels the guest did NOT supply.
///
/// Split from the decode test because the two fail for different reasons and a combined one
/// would report the filter's fault as a decode fault: here the guest declares ONE level, so
/// every level below it is the shader's own filter against `halve_rgba8`.
#[test]
fn gpu_mip_filter_matches_the_cpu() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // 24x24 rather than a power of two: an odd level (3x3 -> 1x1) is where the box filter's
    // edge-clamp rule bites, and it is the rule the two implementations could most easily
    // disagree about.
    let (w, h) = (24u32, 24u32);
    let base_format = 0x81u32;
    let tex_type = 3u32;
    let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
    let mut seed = 0x9e37_79b9_7f4a_7c15u64;
    let bytes: Vec<u8> = (0..ll.bytes as usize)
        .map(|_| {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            (seed >> 33) as u8
        })
        .collect();
    let levels = vitaslop_runtime::render::max_mip_levels(w, h);
    // ONE guest level, so levels 1.. are the shader's own filter.
    let plan = build_plan(base_format, tex_type, w, h, 1, &bytes, false, true);
    let plan = vitaslop_platform::gpu::GpuTranscode { levels, ..plan };
    let got = enc.decode_chain_readback(&device, &queue, &plan);

    let variant = vitaslop_runtime::pvrtc::Variant::from_base_format(base_format).unwrap();
    let mut px = vec![0u8; (w * h * 4) as usize];
    vitaslop_runtime::pvrtc::decode_face(&bytes, w, h, variant, false, &mut px);
    let mut want = vec![(w, h, px)];
    for l in 1..levels as usize {
        let (pw, ph, prev) = &want[l - 1];
        let (nw, nh, next) = vitaslop_runtime::render::halve_rgba8(*pw, *ph, prev);
        want.push((nw, nh, next));
    }
    assert_eq!(got.len(), want.len());
    for (i, ((gw, gh, g), (ww, wh, wv))) in got.iter().zip(&want).enumerate() {
        assert_eq!((gw, gh), (ww, wh), "level {i} dimensions");
        assert_eq!(g, wv, "level {i} ({ww}x{wh}) differs");
    }
}

/// The plan the runtime would build for this texture, assembled here so the test does not need
/// an ETC2 adapter to reach the runtime's own (adapter-gated) builder.
#[allow(clippy::too_many_arguments)]
fn build_plan(
    base_format: u32,
    tex_type: u32,
    w: u32,
    h: u32,
    levels: u32,
    bytes: &[u8],
    two: bool,
    four_bpp: bool,
) -> vitaslop_platform::gpu::GpuTranscode {
    use vitaslop_platform::gpu::{GpuTranscode, SourceCodec, SrcLevel};
    let swizzled = vitaslop_runtime::render::swizzled_type(tex_type);
    let src_levels = (0..levels)
        .map(|l| {
            let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l).unwrap();
            SrcLevel {
                byte_offset: vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l)
                    .unwrap(),
                width: ll.width,
                height: ll.height,
                blocks_x: ll.blocks_x,
                blocks_y: ll.blocks_y,
                padded_x: if swizzled { ll.blocks_x.next_power_of_two() } else { ll.blocks_x },
                padded_y: if swizzled { ll.blocks_y.next_power_of_two() } else { ll.blocks_y },
                swizzled,
            }
        })
        .collect();
    GpuTranscode {
        src: bytes.into(),
        codec: SourceCodec::Pvrtc { two, four_bpp },
        width: w,
        height: h,
        levels,
        src_levels,
    }
}

/// The per-level `copyBufferToTexture` the transcoder records must be one the driver ACCEPTS.
///
/// # This is the test whose absence shipped a broken build
/// The copy extent was each level's LOGICAL size. WebGPU validates a compressed copy against the
/// level's PHYSICAL extent - the logical size rounded up to whole blocks - so a 2x2 mip level of
/// a 4x4-block format has to be copied as 4x4. The driver rejected it with
/// `copySize.height (2) is not a multiple of compressed texture format block height (4)`, the
/// whole command buffer became invalid, and every transcoded texture was created and never
/// written. On the device that read as "no textures are right".
///
/// It was not caught because the copy was believed untestable here: this adapter has no ETC2, so
/// `Transcoder::run` returns `None` and the path stays dormant. That reasoning was wrong. **The
/// copy's rules are properties of the BLOCK GEOMETRY, not of the family** - BC1 and `Etc2Rgb8`
/// are both 4x4 blocks at 8 bytes, BC3 and `Etc2Rgba8` both 4x4 at 16 - so the copy can be driven
/// with whichever block format the adapter DOES have, and it exercises the same arithmetic.
///
/// Native wgpu panics on an uncaptured validation error, so an illegal copy fails this test
/// rather than passing quietly.
#[test]
fn the_recorded_copies_are_accepted_by_the_driver() {
    let Some((device, queue)) = device_with_block_compression() else {
        eprintln!("no GPU adapter with a block-compressed format - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    let f = device.features();
    // Whichever family this adapter has, at both block sizes. The 8-byte and 16-byte cases have
    // different row pitches and so different padding, and only one of them is exercised by any
    // single texture.
    let pairs: Vec<(vitaslop_platform::gpu::BlockFormat, wgpu::TextureFormat)> =
        if f.contains(wgpu::Features::TEXTURE_COMPRESSION_BC) {
            vec![
                (vitaslop_platform::gpu::BlockFormat::Bc1, wgpu::TextureFormat::Bc1RgbaUnorm),
                (vitaslop_platform::gpu::BlockFormat::Bc3, wgpu::TextureFormat::Bc3RgbaUnorm),
            ]
        } else {
            vec![
                (vitaslop_platform::gpu::BlockFormat::Etc2Rgb8, wgpu::TextureFormat::Etc2Rgb8Unorm),
                (
                    vitaslop_platform::gpu::BlockFormat::Etc2Rgba8,
                    wgpu::TextureFormat::Etc2Rgba8Unorm,
                ),
            ]
        };
    // Sizes whose chains reach BELOW the block size, which is where the bug lived, plus a
    // non-square one and the largest atlas this title actually binds.
    for (w, h) in [(2048u32, 2048u32), (1024, 512), (64, 64), (8, 8), (4, 4)] {
        for &(format, wgpu_format) in &pairs {
            enc.copy_geometry_selftest(&device, &queue, w, h, format, wgpu_format);
        }
    }
}

/// The SHIPPED path, end to end, into a real ETC2 texture on a real adapter, read back and
/// compared against the CPU pipeline block for block.
///
/// # Why this exists, and why "the desktop has no ETC2" was wrong
/// Every piece of the transcoder was verified individually - the PVRTC decode, the box filter and
/// the ETC2 encoder are each bit-identical to the CPU code they replace - and `Transcoder::run`
/// itself, which wires them together and copies the result into a texture, was never executed
/// anywhere. It was declared untestable because the default adapter here exposes only BC. That
/// was a statement about ONE adapter, not about the machine: `enumerate_adapters` finds an Intel
/// Arc iGPU on Vulkan that exposes **bc AND etc2**, and everything the shipped path does runs on
/// it unchanged.
///
/// The cost of not looking was a build that reached the user's phone with every transcoded
/// texture created and never written.
///
/// What this checks that nothing else does: the scratch buffer sizes, the uniform slot offsets
/// and dynamic offsets, the dispatch counts, the ORDER of decode -> filter -> encode inside one
/// compute pass (the mip filter reads what the dispatch before it wrote), the row padding, and
/// the per-level copies - by reading the finished texture's actual bytes.
#[test]
fn gpu_transcode_round_trips_through_a_real_etc2_texture() {
    let Some((device, queue)) = device_with_etc2() else {
        eprintln!("no adapter on this machine exposes ETC2 - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Every (source, target) pair the device actually takes: both PVRTC generations at both bit
    // rates, both addressing modes, and the BC formats an ETC2-only adapter has to re-encode -
    // against both ETC2 targets, because the alpha one emits a second block per 4x4 and so has a
    // different row pitch, a different buffer size and a different copy.
    for base_format in [0x80u32, 0x81, 0x82, 0x83, 0x85, 0x86, 0x87] {
        for tex_type in [0u32, 3] {
            for alpha in [false, true] {
                round_trip_one(&device, &queue, &enc, base_format, tex_type, alpha);
            }
        }
    }
}

fn round_trip_one(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    enc: &Transcoder,
    base_format: u32,
    tex_type: u32,
    alpha: bool,
) {
    use vitaslop_platform::gpu::{BlockFormat, CompressedData, CompressedUpload, SourceCodec};
    // 32x32, so the chain runs below the block size - which is where the copy extent was wrong.
    let (w, h) = (32u32, 32u32);
    let label = format!("{base_format:#04x} type {tex_type} alpha {alpha}");
    let levels = vitaslop_runtime::render::max_mip_levels(w, h);
    let mut total = 0usize;
    for l in 0..levels {
        let Some(ll) = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l)
        else {
            break;
        };
        total += ll.bytes as usize;
    }
    let mut seed = 0x1234_5678_9abc_def0u64;
    let bytes: Vec<u8> = (0..total)
        .map(|_| {
            seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            (seed >> 33) as u8
        })
        .collect();
    // The codec the runtime would pick for this base format, chosen the same way it does.
    let codec = match vitaslop_runtime::pvrtc::Variant::from_base_format(base_format) {
        Some(v) => SourceCodec::Pvrtc { two: v.two, four_bpp: v.four_bpp },
        None => SourceCodec::Bc { base_format },
    };
    let mut plan = build_plan(base_format, tex_type, w, h, levels, &bytes, false, true);
    plan.codec = codec;
    let format = if alpha { BlockFormat::Etc2Rgba8 } else { BlockFormat::Etc2Rgb8 };
    let block_bytes = format.block_bytes();
    let upload = CompressedUpload {
        format,
        width: w,
        height: h,
        levels,
        transcoded: true,
        data: CompressedData::Gpu(plan.clone()),
    };

    let texture = enc
        .run(&device, &queue, &upload, &plan, false)
        .expect("this adapter has ETC2, so the transcode must not decline");

    // The CPU pipeline over the same bytes: decode every guest level, then encode each. Each of
    // those steps is separately proved identical to its shader, so any difference here is in the
    // WIRING - which is the point.
    let mut chain: Vec<(u32, u32, Vec<u8>)> = Vec::new();
    for l in 0..levels {
        let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, l).unwrap();
        let off =
            vitaslop_runtime::render::level_offset(base_format, tex_type, w, h, l).unwrap() as usize;
        let px = match vitaslop_runtime::pvrtc::Variant::from_base_format(base_format) {
            Some(variant) => {
                let mut px = vec![0u8; (ll.width * ll.height * 4) as usize];
                vitaslop_runtime::pvrtc::decode_face(
                    &bytes[off..],
                    ll.width,
                    ll.height,
                    variant,
                    vitaslop_runtime::render::swizzled_type(tex_type),
                    &mut px,
                );
                px
            }
            None => {
                let view = bc_texture(base_format, tex_type, ll.width, ll.height, &bytes[off..]);
                vitaslop_runtime::render::decode_texture_rgba8(&view).2
            }
        };
        chain.push((ll.width, ll.height, px));
    }

    for (i, (lw, lh, rgba)) in chain.iter().enumerate() {
        let want = if alpha {
            vitaslop_runtime::etcenc::encode_etc2_rgba8(*lw, *lh, rgba)
        } else {
            vitaslop_runtime::etcenc::encode_etc2_rgb8(*lw, *lh, rgba)
        };
        let got = read_back_level(device, queue, &texture, i as u32, *lw, *lh, block_bytes);
        assert_eq!(got.len(), want.len(), "{label} level {i} ({lw}x{lh}): block count");
        for (b, (a, e)) in got.chunks(block_bytes as usize).zip(want.chunks(block_bytes as usize)).enumerate()
        {
            assert_eq!(
                a, e,
                "{label} level {i} ({lw}x{lh}) block {b} differs\n  gpu texture {a:02x?}\n  cpu        {e:02x?}"
            );
        }
    }
    texture.destroy();
}

/// One mip level of a compressed texture, read back and unpadded.
fn read_back_level(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    level: u32,
    width: u32,
    height: u32,
    block_bytes: u32,
) -> Vec<u8> {
    let blocks_x = width.div_ceil(4);
    let blocks_y = height.div_ceil(4);
    let row = (blocks_x * block_bytes).div_ceil(256) * 256;
    let size = (row * blocks_y) as u64;
    let buf = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("readback"),
        size,
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let mut enc = device.create_command_encoder(&Default::default());
    enc.copy_texture_to_buffer(
        wgpu::TexelCopyTextureInfo {
            texture,
            mip_level: level,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::TexelCopyBufferInfo {
            buffer: &buf,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: Some(blocks_y),
            },
        },
        wgpu::Extent3d { width: blocks_x * 4, height: blocks_y * 4, depth_or_array_layers: 1 },
    );
    queue.submit([enc.finish()]);
    let slice = buf.slice(..);
    slice.map_async(wgpu::MapMode::Read, |_| {});
    let _ = device.poll(wgpu::PollType::Wait { submission_index: None, timeout: None });
    let view = slice.get_mapped_range().expect("the poll above waited for the map");
    let mut out = Vec::with_capacity((blocks_x * blocks_y * block_bytes) as usize);
    for by in 0..blocks_y {
        let start = (by * row) as usize;
        out.extend_from_slice(&view[start..start + (blocks_x * block_bytes) as usize]);
    }
    drop(view);
    buf.unmap();
    out
}

/// An adapter that exposes ETC2, wherever on this machine it is.
///
/// `request_adapter` returns ONE adapter - the high-performance one - and on this machine that is
/// a discrete NVIDIA part with BC and no ETC2. Enumerating finds the integrated Intel GPU on
/// Vulkan, which has both. The difference between those two calls is the difference between "the
/// shipped path cannot be tested here" and this test.
fn device_with_etc2() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.enumerate_adapters(wgpu::Backends::all()))
        .into_iter()
        .find(|a| a.features().contains(wgpu::Features::TEXTURE_COMPRESSION_ETC2))?;
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-etc2-test"),
        required_features: wgpu::Features::TEXTURE_COMPRESSION_ETC2,
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// A device that has SOME block-compressed format, so the copy can be recorded into a real
/// texture. Which family it is does not matter - see `copy_geometry_selftest`.
fn device_with_block_compression() -> Option<(wgpu::Device, wgpu::Queue)> {
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        force_fallback_adapter: false,
        compatible_surface: None,
        apply_limit_buckets: false,
    }))
    .ok()?;
    let want = adapter.features()
        & (wgpu::Features::TEXTURE_COMPRESSION_BC | wgpu::Features::TEXTURE_COMPRESSION_ETC2);
    if want.is_empty() {
        return None;
    }
    pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("texenc-copy-test"),
        required_features: want,
        required_limits: wgpu::Limits::default(),
        memory_hints: Default::default(),
        trace: wgpu::Trace::Off,
        experimental_features: Default::default(),
    }))
    .ok()
}

/// The EAC ascending-modifier order the shader hard-codes must be the one the CPU DERIVES from
/// the tables.
///
/// The CPU builds it with a compile-time selection sort over each table's eight modifiers,
/// precisely so a hand-copied ordering cannot disagree with the tables. WGSL has no const
/// evaluation that could do the same, so the shader writes it out - and a written-out ordering
/// that drifts from the tables encodes every alpha wrong, silently, in a way no single block
/// comparison would obviously explain. This is the guard for that one constant.
#[test]
fn gpu_eac_order_matches_the_cpu() {
    for table in 0..16 {
        let mut want: Vec<usize> = (0..8).collect();
        want.sort_by_key(|&s| vitaslop_runtime::etcenc::eac_modifier(table, s));
        assert_eq!(
            want,
            vec![3, 2, 1, 0, 4, 5, 6, 7],
            "table {table}'s ascending order is not the one texenc.wgsl hard-codes"
        );
    }
}

/// >>> THE VIDEO PATH HAD NO TEST, AND THAT IS HOW IT WENT BLACK.
///
/// `convert_yuv420p2` is the one transcode that runs every frame a movie is on screen, and it
/// was the only one with no test here. A rewrite of it - moving the output from a storage
/// buffer into a storage TEXTURE, to save a 2 MB buffer and a 2 MB copy per picture - produced
/// a black movie with no validation error anywhere, on a title whose decoded picture in guest
/// memory was demonstrably correct. The only evidence was a screenshot, and a screenshot of a
/// movie is not a repeatable oracle ([[the movie frame a run lands on is not deterministic]]).
///
/// So: one picture, converted on the GPU, read back, and compared against the same BT.601
/// arithmetic done here in Rust. Content-free - the picture is generated below - and it skips
/// cleanly with no adapter.
#[test]
fn gpu_yuv_conversion_matches_the_cpu() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter; skipping");
        return;
    };
    let (w, h) = (64u32, 32u32);
    let (luma_stride, chroma_stride) = (w, w);
    let chroma_offset = luma_stride * h;
    // Structure, not noise: a luma ramp in x, chroma ramps in y, so a plane read at the wrong
    // offset or a chroma pair read in the wrong order cannot come out looking right.
    let mut data = vec![0u8; (chroma_offset + chroma_stride * h.div_ceil(2)) as usize];
    for y in 0..h {
        for x in 0..w {
            data[(y * luma_stride + x) as usize] = (16 + (x * 219 / (w - 1))) as u8;
        }
    }
    for cy in 0..h.div_ceil(2) {
        for cx in 0..w.div_ceil(2) {
            let at = (chroma_offset + cy * chroma_stride + cx * 2) as usize;
            data[at] = (16 + cy * 8) as u8;
            data[at + 1] = (240 - cx * 3) as u8;
        }
    }

    let enc = Transcoder::new(&device);
    for swap_chroma in [false, true] {
        let planes = vitaslop_platform::texenc::PlanarYuv {
            width: w,
            height: h,
            luma_stride,
            chroma_stride,
            chroma_offset,
            swap_chroma,
            data: &data,
        };
        let tex = enc
            .convert_yuv420p2(&device, &queue, &planes)
            .expect("this shape is inside what the shader covers");
        let got = read_back_rgba8(&device, &queue, &tex, w, h);
        for y in 0..h as usize {
            for x in 0..w as usize {
                let luma = data[y * luma_stride as usize + x] as i32;
                let c = chroma_offset as usize
                    + (y / 2) * chroma_stride as usize
                    + (x / 2) * 2;
                let (a, b) = (data[c] as i32, data[c + 1] as i32);
                let (cb, cr) = if swap_chroma { (b, a) } else { (a, b) };
                let want = yuv_to_rgb_reference(luma, cb, cr);
                let at = (y * w as usize + x) * 4;
                assert_eq!(
                    &got[at..at + 4],
                    &want[..],
                    "swap_chroma={swap_chroma} at ({x}, {y})"
                );
            }
        }
    }
}

/// BT.601 studio swing, integer, the same arithmetic `yuv_to_rgb` in `texenc.wgsl` does and the
/// same one `vitaslop_runtime::vita::avcdec` uses on the way back.
fn yuv_to_rgb_reference(y: i32, cb: i32, cr: i32) -> [u8; 4] {
    let yt = (y - 16) * 76309;
    let (u, v) = (cb - 128, cr - 128);
    [
        ((yt + 104597 * v + 32768) >> 16).clamp(0, 255) as u8,
        ((yt - 25675 * u - 53279 * v + 32768) >> 16).clamp(0, 255) as u8,
        ((yt + 132201 * u + 32768) >> 16).clamp(0, 255) as u8,
        255,
    ]
}

/// Read an RGBA8 texture's level 0 back, unpadding the 256-byte-aligned rows.
fn read_back_rgba8(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    width: u32,
    height: u32,
) -> Vec<u8> {
    let row = (width * 4).div_ceil(256) * 256;
    let buf = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("rgba-readback"),
        size: (row * height) as u64,
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let mut enc = device.create_command_encoder(&Default::default());
    enc.copy_texture_to_buffer(
        wgpu::TexelCopyTextureInfo {
            texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::TexelCopyBufferInfo {
            buffer: &buf,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: Some(height),
            },
        },
        wgpu::Extent3d { width, height, depth_or_array_layers: 1 },
    );
    queue.submit([enc.finish()]);
    let slice = buf.slice(..);
    slice.map_async(wgpu::MapMode::Read, |_| {});
    let _ = device.poll(wgpu::PollType::Wait { submission_index: None, timeout: None });
    let view = slice.get_mapped_range().expect("the poll above waited for the map");
    let mut out = Vec::with_capacity((width * height * 4) as usize);
    for y in 0..height {
        let start = (y * row) as usize;
        out.extend_from_slice(&view[start..start + (width * 4) as usize]);
    }
    drop(view);
    buf.unmap();
    out
}

/// >>> THE UN-SWIZZLE ON THE GPU IS THE SAME BYTES AS THE UN-SWIZZLE ON THE CPU, level for
/// >>> level, for every addressing mode and every channel order.
///
/// `expand_rgba8` exists to take the largest single item on the target device off its CPU: that
/// device's own report reads `texture decode by format: 2988.8 MB total - 0x0c raw 2964.5 MB`,
/// and all of it is this - a Morton un-interleave plus a channel permutation, one texel at a
/// time, while its GPU is idle.
///
/// Being a permutation, it *cannot* differ, which is exactly why this test exists. Every claim
/// of that shape in this project that went unchecked turned out to differ somewhere: a level
/// whose padded grid is computed one way here and another way there, a channel order read from
/// the wrong field, a chain whose second level is filtered from the wrong source. The comparison
/// is EXACT - not a mean error, not a PSNR - because the two paths are supposed to produce
/// identical bytes and anything else is a defect, not a tolerance.
///
/// The chain rides along: `expand_rgba8` box-filters levels past the guest's own with the same
/// filter `build_mip_chain` uses, so a level-by-level compare catches an error in the filter
/// that a level-0 compare would hide.
#[test]
fn gpu_raw_expand_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Every combination that changes the ADDRESSING or the channel order, plus a
    // non-power-of-two shape, where the padded Morton grid and the real extent differ.
    for (w, h) in [(32u32, 32u32), (64, 16), (24, 40)] {
        for swizzled in [false, true] {
            for sel in 0..4u32 {
                // SWIZZLED / LINEAR `SceGxmTextureType` selectors.
                let tex_type: u32 = if swizzled { 0 } else { 3 };
                let base_format: u32 = 0x0c; // U8U8U8U8
                // The guest's bytes for level 0. A swizzled level occupies its POWER-OF-TWO
                // padded grid, which for a non-power-of-two extent is larger than the extent.
                let src_texels = if swizzled {
                    (w.next_power_of_two() as usize) * (h.next_power_of_two() as usize)
                } else {
                    (w as usize) * (h as usize)
                };
                let mut seed = 0x9e37_79b9_7f4a_7c15u64;
                let bytes: Vec<u8> = (0..src_texels * 4)
                    .map(|_| {
                        seed = seed
                            .wrapping_mul(6364136223846793005)
                            .wrapping_add(1442695040888963407);
                        (seed >> 33) as u8
                    })
                    .collect();

                let tex = vitaslop_runtime::capture::BoundTexture {
                    unit: 0,
                    base_format,
                    // The channel order lives in bits 12..14 of the format word.
                    swizzle: sel << 12,
                    tex_type,
                    width: w,
                    height: h,
                    stride: w * 4,
                    faces: 1,
                    face_bytes: (src_texels * 4) as u32,
                    levels: 1,
                    data_addr: 0,
                    pixels: bytes.clone().into(),
                    pixels_id: vitaslop_runtime::capture::next_pixels_id(),
                    u_addr_mode: 0,
                    v_addr_mode: 0,
                    lod_bias: 0,
                    min_filter: 0,
                    mag_filter: 0,
                    mip_filter: 0,
                    gamma: 0,
                };

                let Some(plan) = vitaslop_runtime::render::raw_source(&tex) else {
                    panic!("{w}x{h} swizzled={swizzled} sel={sel}: the plan was refused");
                };
                // Run it TWICE into the same texture on the second pass, so the reuse path - the one
                // that writes over a texture the previous contents went into - is what the
                // comparison below actually checks. A fresh-texture-only test would leave the
                // path the running engine takes on almost every frame unexercised.
                let Some(first) = enc.expand_rgba8(&device, &queue, &plan, false, None) else {
                    panic!("{w}x{h} swizzled={swizzled} sel={sel}: the expansion was refused");
                };
                let Some(got) = enc.expand_rgba8(&device, &queue, &plan, false, Some(first)) else {
                    panic!("{w}x{h} swizzled={swizzled} sel={sel}: the expansion was refused");
                };
                // >>> THE BATCH IS WHAT WRITES THE TEXELS. `expand_rgba8` RECORDS its work and
                // hands the texture back; nothing is on the queue until this. Reading back
                // without it compares the CPU decoder against an untouched texture, which is
                // exactly the failure a caller that forgets the flush would ship. Both
                // expansions above are still pending here, so this also covers two textures
                // sharing one submit - the case the sub-allocated scratch exists for.
                enc.flush_raw(&queue);

                // The CPU reference: the same decoder the uploader falls back to, then the same
                // box filter `build_mip_chain` applies - so this compares the two PATHS, not two
                // spellings of one of them.
                let (_, _, level0) = vitaslop_runtime::render::decode_texture_rgba8(&tex);
                let mut want = level0;
                let (mut sw, mut sh) = (w, h);
                for level in 0..plan.levels {
                    if level > 0 {
                        let (dw, dh) = ((sw / 2).max(1), (sh / 2).max(1));
                        let mut dst = vec![0u8; (dw * dh * 4) as usize];
                        for y in 0..dh as usize {
                            for x in 0..dw as usize {
                                for c in 0..4usize {
                                    let x0 = (2 * x).min(sw as usize - 1);
                                    let x1 = (2 * x + 1).min(sw as usize - 1);
                                    let y0 = (2 * y).min(sh as usize - 1);
                                    let y1 = (2 * y + 1).min(sh as usize - 1);
                                    let at = |xx: usize, yy: usize| {
                                        want[(yy * sw as usize + xx) * 4 + c] as u32
                                    };
                                    dst[(y * dw as usize + x) * 4 + c] =
                                        ((at(x0, y0) + at(x1, y0) + at(x0, y1) + at(x1, y1) + 2)
                                            / 4) as u8;
                                }
                            }
                        }
                        want = dst;
                        sw = dw;
                        sh = dh;
                    }
                    let mine = read_back_rgba8_level(&device, &queue, &got, level, sw, sh);
                    assert_eq!(
                        mine, want,
                        "{w}x{h} swizzled={swizzled} sel={sel} level {level} ({sw}x{sh}): the GPU \
                         un-swizzle and the CPU decoder disagree, and a permutation cannot",
                    );
                }
            }
        }
    }
}

/// The GPU BC expansion is the CPU BC decoder, byte for byte, over the whole mip chain.
///
/// `block_source` exists to take the LARGEST remaining CPU item on the target device off it: a
/// GPU with no BC support expands every compressed guest texture to RGBA8, and that device's own
/// report reads one frame's working set of 130 MB with `0x85 BC -> RGBA8 x136 (98.1 MB)` in it,
/// while its slowest frames are ~600 ms at ordinary host-call counts.
///
/// The claim being made is "the same bytes, somewhere else", and that claim is exactly the kind
/// this project has been wrong about before - a padded Morton grid computed one way here and
/// another there, a level filtered from the wrong source, a dispatch grid sized in texels where
/// the shader indexes blocks. So the comparison is EXACT and it covers every level, not just
/// level 0: `gpu_bc_matches_the_cpu_decoder` already pins the block decoder on its own, and this
/// pins the PATH that carries it - the plan `block_source` builds, the block-sized dispatch, the
/// generated chain and the row-aligned copy-out.
#[test]
fn gpu_bc_expand_matches_the_cpu_decoder() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // All three BC families (BC1's punch-through mode, BC2's raw nibbles, BC3's alpha ramp),
    // both addressing modes, and a non-power-of-two shape where the padded block grid and the
    // real block extent differ.
    for base_format in [0x85u32, 0x86, 0x87] {
        for swizzled in [false, true] {
            for (w, h) in [(32u32, 32u32), (64, 16), (24, 40)] {
                let tex_type: u32 = if swizzled { 0 } else { 3 };
                let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0)
                    .unwrap();
                let mut seed = 0x0123_4567_89ab_cdefu64;
                let bytes: Vec<u8> = (0..ll.bytes as usize)
                    .map(|_| {
                        seed = seed
                            .wrapping_mul(6364136223846793005)
                            .wrapping_add(1442695040888963407);
                        (seed >> 33) as u8
                    })
                    .collect();
                let tex = bc_texture(base_format, tex_type, w, h, &bytes);
                let label = format!("{base_format:#04x} {w}x{h} swizzled={swizzled}");

                let Some(plan) = vitaslop_runtime::render::block_source(&tex) else {
                    panic!("{label}: the plan was refused");
                };
                // Twice, the second time into the first one's texture: the reuse path is what
                // the running engine takes on almost every frame, and a fresh-texture-only
                // test would leave it unexercised.
                let Some(first) = enc.expand_rgba8(&device, &queue, &plan, false, None) else {
                    panic!("{label}: the expansion was refused");
                };
                let Some(got) = enc.expand_rgba8(&device, &queue, &plan, false, Some(first))
                else {
                    panic!("{label}: the expansion was refused");
                };
                // The recorded work goes to the queue here - see the same call in
                // `gpu_raw_expand_matches_the_cpu_decoder` for why a readback without it
                // compares against an untouched texture.
                enc.flush_raw(&queue);

                // The CPU reference: the decoder the uploader falls back to, then the same box
                // filter `build_mip_chain` applies - so this compares the two PATHS.
                let (_, _, level0) = vitaslop_runtime::render::decode_texture_rgba8(&tex);
                let mut want = level0;
                let (mut sw, mut sh) = (w, h);
                for level in 0..plan.levels {
                    if level > 0 {
                        let (nw, nh, next) =
                            vitaslop_runtime::render::halve_rgba8(sw, sh, &want);
                        want = next;
                        sw = nw;
                        sh = nh;
                    }
                    let mine = read_back_rgba8_level(&device, &queue, &got, level, sw, sh);
                    assert_eq!(
                        mine, want,
                        "{label} level {level} ({sw}x{sh}): the GPU block expansion and the CPU                          decoder disagree, and they are supposed to be one function",
                    );
                }
            }
        }
    }
}

/// [`read_back_rgba8`] for one MIP LEVEL. The chain is the half of this that a level-0-only
/// comparison would not check, and the filter is where an off-by-one hides.
fn read_back_rgba8_level(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    texture: &wgpu::Texture,
    level: u32,
    width: u32,
    height: u32,
) -> Vec<u8> {
    let row = (width * 4).div_ceil(256) * 256;
    let buf = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("readback-level"),
        size: (row * height) as u64,
        usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    let mut enc = device.create_command_encoder(&Default::default());
    enc.copy_texture_to_buffer(
        wgpu::TexelCopyTextureInfo {
            texture,
            mip_level: level,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::TexelCopyBufferInfo {
            buffer: &buf,
            layout: wgpu::TexelCopyBufferLayout {
                offset: 0,
                bytes_per_row: Some(row),
                rows_per_image: Some(height),
            },
        },
        wgpu::Extent3d { width, height, depth_or_array_layers: 1 },
    );
    queue.submit([enc.finish()]);
    let slice = buf.slice(..);
    slice.map_async(wgpu::MapMode::Read, |_| {});
    let _ = device.poll(wgpu::PollType::Wait { submission_index: None, timeout: None });
    let view = slice.get_mapped_range().expect("the poll above waited for the map");
    let mut out = Vec::with_capacity((width * height * 4) as usize);
    for y in 0..height {
        let start = (y * row) as usize;
        out.extend_from_slice(&view[start..start + (width * 4) as usize]);
    }
    drop(view);
    buf.unmap();
    out
}

/// >>> SEVERAL DIFFERENT TEXTURES EXPANDED INTO ONE SUBMIT ALL COME OUT RIGHT.
///
/// # What this pins, and why the other two oracles cannot
/// `gpu_bc_expand_matches_the_cpu_decoder` and its uncompressed twin expand the SAME plan twice
/// and compare the result, so both of their expansions read the same source bytes. That would
/// pass just as happily if every texture in a batch read texture zero's bytes - which is the
/// exact failure mode the batching introduces, because `queue.write_buffer` is not ordered with
/// the encoder: every write queued before a submit lands before ALL of that submit's commands, so
/// a scratch buffer shared by two textures would hand the first one the second one's source.
///
/// So this expands textures whose contents DIFFER, holds them all in one batch, and checks each
/// against its own CPU decode. A sub-allocation bug shows up as texture N carrying texture M's
/// image, which is precisely the kind of defect that reaches a device as "one thing on screen is
/// wearing another thing's texture" and nothing in a log to say so.
///
/// The shapes differ too, so the batch's running offsets are not a multiple of one stride - a
/// test where every texture is the same size can be passed by an implementation that gets the
/// alignment wrong.
#[test]
fn gpu_expand_batches_several_textures_into_one_submit() {
    let Some((device, queue)) = device() else {
        eprintln!("no GPU adapter - skipping");
        return;
    };
    let enc = Transcoder::new(&device);
    // Distinct shapes AND distinct contents. `seed` is folded into the bytes so no two of these
    // can be confused for one another, which is the whole point.
    let shapes: [(u32, u32, u32); 5] =
        [(0x85, 32, 32), (0x87, 24, 40), (0x85, 64, 16), (0x86, 16, 16), (0x87, 32, 8)];
    let mut fixtures = Vec::new();
    for (i, &(base_format, w, h)) in shapes.iter().enumerate() {
        let tex_type = 3;
        let ll = vitaslop_runtime::render::level_layout(base_format, tex_type, w, h, 0).unwrap();
        let mut seed = 0x1000_0000_0000_0001u64.wrapping_mul(i as u64 + 1);
        let bytes: Vec<u8> = (0..ll.bytes as usize)
            .map(|_| {
                seed = seed
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                (seed >> 33) as u8
            })
            .collect();
        fixtures.push((base_format, w, h, bc_texture(base_format, tex_type, w, h, &bytes)));
    }
    // >>> WARM THE SCRATCH FIRST, because a batch cannot span a scratch that has to GROW - the
    // buffers a pending batch is recorded against cannot be destroyed under it, so `expand_rgba8`
    // flushes before it re-allocates. The scratch grows to the largest seen in every axis and
    // then stops, which is why a running title batches: its texture sizes settle within the first
    // frames of a screen. A test that skipped this would be measuring the first frame after a
    // resolution change and nothing else.
    for (_, _, _, tex) in &fixtures {
        if let Some(plan) = vitaslop_runtime::render::block_source(tex) {
            let _ = enc.expand_rgba8(&device, &queue, &plan, false, None);
        }
    }
    enc.flush_raw(&queue);
    // EVERY expansion first, THEN one flush - so all five are in flight together and each one's
    // source has to have landed in its own range of the shared scratch.
    let mut got = Vec::new();
    for (base_format, w, h, tex) in &fixtures {
        let Some(plan) = vitaslop_runtime::render::block_source(tex) else {
            panic!("{base_format:#04x} {w}x{h}: the plan was refused");
        };
        let Some(t) = enc.expand_rgba8(&device, &queue, &plan, false, None) else {
            panic!("{base_format:#04x} {w}x{h}: the expansion was refused");
        };
        got.push(t);
    }
    assert_eq!(
        enc.raw_batch_pending(),
        fixtures.len() as u32,
        "the five expansions did not share a batch, so this test is not testing what it says \
         it is - it would pass on a per-texture submit"
    );
    enc.flush_raw(&queue);
    for (i, (base_format, w, h, tex)) in fixtures.iter().enumerate() {
        let (_, _, want) = vitaslop_runtime::render::decode_texture_rgba8(tex);
        let mine = read_back_rgba8_level(&device, &queue, &got[i], 0, *w, *h);
        assert_eq!(
            mine, want,
            "{base_format:#04x} {w}x{h} (texture {i} of a five-texture batch): the GPU expansion \
             and the CPU decoder disagree. A batch shares one scratch buffer, so the usual cause \
             is this texture reading another one's source bytes."
        );
    }
}
